---
name: Gradle

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    uses: jburel/action-workflows/.github/workflows/gradle_build.yml@608e02b88d75c240f96a0548e435afee625b3084
  publish_snapshots:
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == 'true'
    needs: build
    uses: jburel/action-workflows/.github/workflows/gradle_publish.yml@608e02b88d75c240f96a0548e435afee625b3084
    with:
      ARTIFACTORY_URL: "snapshots"
    secrets:
      ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
  publish:
    needs: build
    if: startsWith(github.ref, 'refs/tags')
    uses: jburel/action-workflows/.github/workflows/gradle_publish.yml@608e02b88d75c240f96a0548e435afee625b3084
    with:
      ARTIFACTORY_URL: "staging"
    secrets:
      ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
